In [11]:
import tensorflow as tf

In [12]:
print(('Your Tensorflow version: {0}'.format(tf.__version__)))

Your Tensorflow version: 2.5.0


In [16]:
A = tf.constant([[4,3],
                     [6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [17]:
B = tf.Variable([[4,3],
                     [6,1]])
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [18]:
AB_concatenated = tf.concat(values=[A,B],axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 4, 3],
       [6, 1, 6, 1]], dtype=int32)>

In [23]:
tensor = tf.Variable(tf.random.uniform([2,3],dtype=tf.float64))
tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[0.33407038, 0.34374525, 0.33999779],
       [0.88825132, 0.29077649, 0.1094457 ]])>

In [ ]:
tensor = tf.Variable(tf.reshape[2,3],dtype=tf.float64))
tensor