In [1]:
import tensorflow as tf

In [2]:
print(('Your Tensorflow version: {0}'.format(tf.__version__)))

Your Tensorflow version: 2.5.0


In [3]:
A = tf.constant([[4,3],
                     [6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [4]:
B = tf.Variable([[4,3],
                     [6,1]])
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [5]:
AB_concatenated = tf.concat(values=[A,B],axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 4, 3],
       [6, 1, 6, 1]], dtype=int32)>

In [6]:
tensor = tf.Variable(tf.random.uniform([2,3],dtype=tf.float64))
tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[0.23629509, 0.67055965, 0.93218712],
       [0.21641447, 0.04736508, 0.68128948]])>

In [7]:
tensor = tf.reshape(tensor=tensor,shape=[3,2])
tensor

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.23629509, 0.67055965],
       [0.93218712, 0.21641447],
       [0.04736508, 0.68128948]])>

In [8]:
tf.cast(tensor, tf.int64)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]])>

In [9]:
tf.eye(2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [14]:
# Making Identity Matrix
tf.eye(2, num_columns=3, dtype=tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0]], dtype=int32)>

In [17]:
rows, columns = tensor.shape
print('rows:',rows,'coulumns:',columns)

rows: 3 coulumns: 2
